name: compass
description: A compass ap.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.6
  flutter_bloc: ^6.1.2
  flutter_compass: ^0.5.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  permission_handler: ^5.1.0+2

dev_dependencies:
  build_runner:
  faker: ^1.3.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  lint: ^1.3.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/compass.png